import { StyleSheet } from 'react-native';
import { tokens } from '../tokens';

/** Layout + typography for the pink app shell — no white chrome. */
export const shellStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.spacing.screenHorizontal,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
    minHeight: 56,
  },
  headerSide: { width: 70 },
  headerTitle: {
    ...tokens.typography.titleSmall,
    color: tokens.colors.textOnBrand,
  },
  headerBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: tokens.radius.sm,
    backgroundColor: tokens.colors.shellIconBtn,
  },
  headerBtnCompact: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: tokens.radius.sm,
    backgroundColor: tokens.colors.shellIconBtn,
    minWidth: 70,
    alignItems: 'center',
  },
  headerBtnText: {
    ...tokens.typography.label,
    color: tokens.colors.textOnBrand,
  },
  sectionTitle: {
    ...tokens.typography.caption,
    color: tokens.colors.textMutedOnBrand,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  heroWordmark: {
    fontSize: 44,
    lineHeight: 52,
    color: tokens.colors.textOnBrand,
    marginTop: 4,
    marginBottom: 4,
  },
  heroHeadline: {
    ...tokens.typography.titleSmall,
    color: tokens.colors.textOnBrand,
    marginTop: 4,
  },
  heroSub: {
    ...tokens.typography.bodySmall,
    color: tokens.colors.textMutedOnBrand,
    marginTop: 8,
    lineHeight: 21,
  },
  emptyBlock: {
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: tokens.colors.shellIconBtn,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyTitle: {
    ...tokens.typography.titleSmall,
    color: tokens.colors.textOnBrand,
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyText: {
    ...tokens.typography.bodySmall,
    color: tokens.colors.textMutedOnBrand,
    textAlign: 'center',
    lineHeight: 20,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 4,
    marginBottom: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: tokens.colors.shellRowBorder,
  },
  featureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  featureCell: {
    width: '48%',
    flexGrow: 1,
    flexBasis: '46%',
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    minWidth: 0,
  },
  featureCellTitle: {
    ...tokens.typography.label,
    fontSize: 13,
    color: tokens.colors.textOnBrand,
    textAlign: 'center',
  },
  featureCellCaption: {
    ...tokens.typography.caption,
    color: tokens.colors.textMutedOnBrand,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 16,
  },
  noteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 4,
  },
  noteTitle: {
    ...tokens.typography.label,
    color: tokens.colors.textOnBrand,
    marginBottom: 4,
  },
  noteBody: {
    ...tokens.typography.bodySmall,
    color: tokens.colors.textMutedOnBrand,
    lineHeight: 20,
  },
  stateTitle: {
    ...tokens.typography.titleSmall,
    color: tokens.colors.textOnBrand,
    marginBottom: 8,
    textAlign: 'center',
  },
  stateText: {
    ...tokens.typography.bodySmall,
    color: tokens.colors.textMutedOnBrand,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20,
  },
});
