/** Placeholder profiles for admin screenshot studio when the feed is empty. */
export const SCREENSHOT_DEMO_PROFILES = [
  {
    id: 'screenshot-demo-1',
    uid: 'screenshot-demo-1',
    name: 'Amina',
    age: 24,
    gender: 'female',
    bio: 'Coffee, books, and conversation that actually goes somewhere.',
    city: 'London',
    country: 'United Kingdom',
    countryOfResidence: 'United Kingdom',
    images: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80'],
    lastSeen: Date.now() - 5 * 60 * 1000,
  },
  {
    id: 'screenshot-demo-2',
    uid: 'screenshot-demo-2',
    name: 'Yusuf',
    age: 27,
    gender: 'male',
    bio: 'Building things, staying active, looking for something real.',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryOfResidence: 'United Arab Emirates',
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    lastSeen: Date.now() - 20 * 60 * 1000,
  },
  {
    id: 'screenshot-demo-3',
    uid: 'screenshot-demo-3',
    name: 'Sara',
    age: 26,
    gender: 'female',
    bio: 'Designer. Early riser. Here for intention, not games.',
    city: 'Toronto',
    country: 'Canada',
    countryOfResidence: 'Canada',
    images: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80'],
    lastSeen: Date.now() - 2 * 60 * 60 * 1000,
  },
];
